title: Recuperaci칩n y acceso a la informaci칩n
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://www.recuperacion-acceso-informacion.es/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: P치gina principal
    url: /index.html
 # - title: Sobre nosotros
 #   url: /about
  - title: Lenguajes de la web sem치ntica
    url: /contact

social:
  github: brianmaierjr
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com
  linkedin: brianmaierjr

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
